apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 3
  selector:
    matchLabels:
      name: apiserver
  template:
    metadata:
      labels:
        name: apiserver
    spec:
      containers:
      - name: apiserver
        image: ghcr.io/heiyiu/scratch:v0.0.6
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_USER
          value: apiuser
        - name: POSTGRES_DB
          value: spay
        - name: POSTGRES_HOST
          value: {{ .Release.Name }}-pg
        - name: POSTGRES_PASSWORD # 
          valueFrom:
            secretKeyRef:
              name: pgpasssecret # this should match the secret name used with kubeseal
              key: pgpass # this should match the key name used with kubeseal