apiVersion: v1
kind: Service
metadata:
  name: apiserver-service
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    name: apiserver
status:
  loadBalancer: {}