pg:
  image:
    debug: true
  primary:
    initdb:
      scripts:
        create_user_and_load_data.sql: |
          CREATE USER apiuser WITH PASSWORD 'password';
          CREATE DATABASE spay;
          \c spay;
          CREATE TABLE users(id int, name VARCHAR(70), PRIMARY KEY (id));
          CREATE INDEX name_idx ON users (name); 
          GRANT SELECT, INSERT, UPDATE ON users TO apiuser;
          \copy users (id, name) FROM '/dbinit/userdata.csv' WITH (FORMAT csv, HEADER true);
    extraVolumes:
      - name: userdata-csv
        configMap:
          name: userdata-csv
    extraVolumeMounts:
      - name: userdata-csv
        mountPath: /dbinit/userdata.csv
        subPath: userdata.csv