pg:
  auth:
    username: user
    password: password
    database: spay
  image:
    debug: true
  primary:
    extraVolumes:
      - name: userdata-csv
        configMap:
          name: userdata-csv
    extraVolumeMounts:
      - name: userdata-csv
        mountPath: /dbinit/userdata.csv
        subPath: userdata.csv
    initdb:
      scripts:
        init.sql: |
          CREATE TABLE users(id int, name VARCHAR(70), PRIMARY KEY (id));
          CREATE INDEX name_idx ON users (name); 
          COPY users (id, name) FROM '/dbinit/userdata.csv' WITH (FORMAT csv, HEADER true); 